### ISSUE TITLE
Normalized URIs begin with https:// rather than http://

### ISSUE THREAD

**Issue by milepost183** [niksite/url-normalize#14]
Version 1.2.1 emits normalized URIs that begin with http://. In some later version, a change was made so that they now begin with https:// instead. This was observed with python 2.7.9.

**Comment by wimmuskee** [comment]
This happens only when the protocol parts isn't provided. If the input is http:// the normalized url also has http:// .

**Comment by milepost183** [comment]
Confirmed--my logic was not providing the protocol parts.

**Comment by gilcye** [comment]
I agree, it should start with HTTP when protocol is not provided

**Comment by niksite** [comment]
Since version 1.4.1 we support an optional param `default_scheme` so you could set `http` scheme as a default if required:
```
url_normalize(url, default_scheme="http")
```
