### ISSUE TITLE
Normalization lowercases path, resulting in broken urls

### ISSUE THREAD

**Issue by lifenautjoe** [niksite/url-normalize#21]
Some URLs on the internet are case sensitive. Most importantly youtube.

The library takes a valid youtube URL such as `https://youtu.be/29sCF3NYBvw` and lowercases it all into `https://youtu.be/29scf3nybvw` which is no longer a valid youtube URL.

Please remove this functionality.

**Comment by niksite** [comment]
@lifenautjoe Could you please provide a reproducible scenario? 

I cannot reproduce your example locally:
```
>>> from url_normalize import url_normalize
>>> url_normalize('https://youtu.be/29sCF3NYBvw')
'https://youtu.be/29sCF3NYBvw'
```
