### ISSUE TITLE
Remove trailing slashes

### ISSUE THREAD

**Issue by josalvatorre** [niksite/url-normalize#30]
Have you guys considered removing trailing slashes? Right now, I get two different strings depending on whether I include the trailing slash.
```
Python 3.10.3 (main, Mar 25 2022, 16:40:56) [Clang 13.1.6 (clang-1316.0.21.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from url_normalize import url_normalize
>>> url_normalize('https://www.levels.fyi/company')
'https://www.levels.fyi/company'
>>> url_normalize('https://www.levels.fyi/company/')
'https://www.levels.fyi/company/'
```
Is there a situation where that slash means anything?

**Comment by niksite** [comment]
Those are different urls. They usually work the same but occasionally only one of them working.

**Comment by josalvatorre** [comment]
> Those are different urls. They usually work the same but occasionally only one of them working.

Thank you for clarifying. Never mind.
