### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by malexmave** [niksite/url-normalize#5]
I noticed that url-normalize has not yet been put under a specific license. As we are using it in a system of ours, we would be interested in knowing under which terms it can be used. Can you [choose a license](http://choosealicense.org) and add it to the repository?

**Comment by niksite** [comment]
It's "Python" license here.

**Comment by malexmave** [comment]
Thanks. Just to be sure: You're referring to the [PSF License](https://docs.python.org/3/license.html)?

**Comment by niksite** [comment]
Yes, PSF.
